//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspireWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string EventFullName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Venue { get; set; }
        public string PONumber { get; set; }
        public Nullable<int> POBudget { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> RecievedID { get; set; }
        public string ProjectStatus { get; set; }
    }
}
