//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspireWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string TaxID { get; set; }
        public Nullable<bool> Individual { get; set; }
        public string BankInfo { get; set; }
        public string Note { get; set; }
    }
}
